### 10-11 Spectral resolution of the identity. 

Suppose A ∈ $R^{n×n}$ has n linearly independent eigenvectors
p1 , . . . , pn, $p^T_i p_i$  = 1, i = 1, . . . , n, with associated eigenvalues $λ_i$ . Let P = [p1 · · · pn ] and
Q = P −1 . Let $q_i$ be the ith row of Q. <br\>
(a) Let $R_k = p_kq_k^T$ . What is the range of $R_k$ ? What is the rank of $R_k$ ? Can you describe
the null space of R_k ? <br/>
(b) Show that R_i R_j = 0 for i $\neq$ j. What is $R_i^2$ ?<br/>
(c) Show that

$$(sI − A)^{−1} = \sum_{k=1}^{n} \frac{R_k}{s-\lambda_k}$$ 

Note that this is a partial fraction expansion of $(sI − A)^{−1}$. For this reason the Ri’s are
called the residue matrices of A.<br/>
(d) Show that R1 + · · · + Rn = I. For this reason the residue matrices are said to constitute
a resolution of the identity.<br/>
(e) Find the residue matrices for A = [[ 1 0][1 −2]]
both ways described above (i.e., find P and Q and then calculate the R’s, and then do
a partial fraction expansion of $(sI − A)^{−1}$ to find the R’s).


### (A)

using <br\>
$
Q P = I = PQ\\
also\ p_k^Tq_k = 1\\
\Rightarrow p_1q_1^T + \cdots + p_kq_k^T + \cdots p_nq_n^T  = I \\
using, p_kp_k^T = 1 \\
one\ can\ show, p_k = q_k \\
Range(R_k) = span\{p_k\}\ so\ dim\ is\ 1$

### (B)

use simple manipulations

### (C)

write A into eigen decomposition and open formula (sI-A) then its inverse is simply inverse of diagonal matrix (s$I$ - $\Lambda$).

### (D)

this has been shown in (A)

### (E)

In [85]:
import numpy as np
np.set_printoptions(suppress=True)

A = np.asarray([[1,0],[1,-2]])
print(A)

[[ 1  0]
 [ 1 -2]]


In [86]:
#ff, v = np.linalg.eig(A)

In [87]:
#v.T.dot(v)

P = np.asarray([[3/(np.sqrt(10)), 0],[1/(np.sqrt(10)),1]])
print(P)

[[0.9486833  0.        ]
 [0.31622777 1.        ]]


In [88]:
# check if orthogonal
# n linearly independent eigenvector not neccessarily "orthogonal"
# but can be normalized.
print(P.dot(P))
print(A.dot(P[:,0]))

[[0.9        0.        ]
 [0.61622777 1.        ]]
[0.9486833  0.31622777]


In [89]:
Q = np.linalg.inv(P)
print(Q)
# Compute corresponding eigenvalues

print((Q.dot(A)).dot(P))

[[ 1.05409255  0.        ]
 [-0.33333333  1.        ]]
[[ 1.  0.]
 [-0. -2.]]


In [102]:
# check
#Q.T.dot(Q)

print(P)
print(Q)

[[0.9486833  0.        ]
 [0.31622777 1.        ]]
[[ 1.05409255  0.        ]
 [-0.33333333  1.        ]]


In [103]:
q1 = np.expand_dims(Q[0,:],axis=-1)
print(q1)

p1 = np.expand_dims(P[:,0],axis=-1)
print(p1)

R1 = np.matmul(p1, q1.T)
print(R1)

[[1.05409255]
 [0.        ]]
[[0.9486833 ]
 [0.31622777]]
[[1.         0.        ]
 [0.33333333 0.        ]]


In [104]:
q2 = np.expand_dims(Q[1,:],axis=-1)
#print(q1.shape)

p2 = np.expand_dims(P[:,1],axis=-1)
#print(p1.shape)

R2 = p2.dot(q2.T)
print(R2)

[[ 0.          0.        ]
 [-0.33333333  1.        ]]


In [106]:
# Note 
print(np.all(R1 + R2 == np.eye(2)))

True


In [107]:
import sympy as sp

In [114]:
s = sp.symbols('s')

sI_A = sp.Matrix(s*sp.eye(2) - A)
print(sI_A)

Matrix([[s - 1, 0], [-1, s + 2]])


In [116]:
print(sI_A ** -1)

Matrix([[1/(s - 1), (-(-s + 1)*(s + 2) - (s - 1)*(s + 2))/((s - 1)*(s + 2))], [1/((s - 1)*(s + 2)), -(-s + 1)/((s - 1)*(s + 2))]])
