### 15-21 Worst and best direction of excitation for a suspension system

### Answer

Since the whole y(t) linearly depends upon the q then the net equation is with only 3 variable each with respect to one direction 

So D becomes D = $||Jq||$

so equation are some Matrix J and $(x^T J x)$ such that $||q|| = 1$

Solution to above problem is standard q corresponding to maximum eigenvalue for D maximum and q be eigenvector corresponding to minimum eigenvalue for D minimum.

In [16]:
import json
from pprint import pprint
import numpy as np

with open('worst_susp_data.json') as f:
    data = json.load(f)
    
#pprint(data)

In [15]:
A = np.asarray(data['A']['data'])
B = np.asarray(data['B']['data'])
C = np.asarray(data['C']['data'])

v = np.asarray(data['v']['data'])

print(A.shape, B.shape, C.shape, v.shape)

(5, 5) (5, 3) (3, 5) (100, 1)


In [21]:
#print(v)
M = v[0]*C.dot(B)
print(M)

[[-0.  0. -0.]
 [ 0. -0.  0.]
 [ 0. -0.  0.]]


#### The whole relation is analysed after opening each relation in vector form to finally realizing it is linear form,  not as given above.